

# testintg client 

cd ..
time ./client $1 "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"

time ./client $1 "testando unicode symbols: 😻😘♥☕"

time ./client $1 "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean tristique velit eget fermentum posuere. In hac habitasse platea dictumst. Duis condimentum, urna ac placerat ultricies, purus augue rutrum mi, eget vehicula augue sem eu eros. Vivamus viverra libero et bibendum lacinia. Suspendisse potenti. In rhoncus purus vitae egestas placerat. Proin a aliquet metus. Aliquam erat volutpat. Etiam ante neque, varius id velit non, convallis facilisis dui.

Aliquam erat volutpat. Quisque nibh urna, dapibus volutpat semper id, cursus ac quam. Maecenas commodo nibh eu ipsum faucibus ornare. Donec in diam ut nisi consectetur placerat sagittis vitae elit. Vestibulum sed nisi non ante sollicitudin dapibus. Vestibulum lorem metus, tincidunt in porttitor id, efficitur tincidunt quam. Cras molestie enim sed leo aliquam blandit. Aenean vulputate feugiat ornare. Sed consequat dolor quis est euismod, eget aliquet est interdum. Etiam libero urna, varius vitae condimentum id, dignissim ut quam. Suspendisse et nisi ac tortor pretium sollicitudin id vel tellus.

Proin odio libero, venenatis sit amet egestas vitae, accumsan in ex. Ut quis urna non sem bibendum vehicula. In hac habitasse platea dictumst. Cras mattis quam at lorem sagittis bibendum. Integer quis purus lorem. Quisque vestibulum libero odio, ac efficitur erat pharetra a. Pellentesque id dictum sapien, quis viverra metus. Vivamus sed nisi tincidunt, pellentesque purus id, fringilla ipsum. Ut blandit a ex sed vehicula.

Phasellus nec sollicitudin lacus, non sagittis felis. Fusce nunc eros, interdum eget vestibulum vel, tincidunt non ante. Nulla at aliquam massa, varius posuere nibh. Fusce urna risus, mollis non vulputate dignissim, dapibus eget tortor. Proin vestibulum tellus et felis commodo, ut aliquam nunc ultricies. Nam consequat purus facilisis dui aliquet accumsan. Integer ante sem, tristique sit amet elit sit amet, fringilla molestie ex. Aliquam eget aliquam dolor. Integer eu quam nec magna sodales viverra eget mollis risus. Praesent tincidunt vitae ligula eget maximus. Nulla elementum vitae dolor sed mollis. Nulla fermentum nibh sed ligula hendrerit imperdiet. Vivamus sed magna a nunc imperdiet pharetra ut in justo. Aliquam sit amet malesuada tellus, ac sodales magna. Suspendisse accumsan vitae nulla vitae malesuada. Morbi semper eros eu est sodales, vitae gravida tellus tincidunt.

Aliquam vitae lacinia felis. Maecenas dictum dolor sapien, id convallis leo lacinia vitae. Nulla a metus purus. Ut finibus id neque in placerat. Proin sodales non lectus quis bibendum. Proin elementum a mauris non fringilla. Nulla facilisi.

Aliquam suscipit mauris at dolor consectetur, eget sagittis neque consequat. Proin pretium turpis purus, at sollicitudin purus iaculis id. Etiam laoreet ipsum a consectetur vehicula. Aliquam at auctor libero. Donec ornare dolor a est ullamcorper feugiat. Ut eget fermentum lectus. Donec volutpat vulputate lectus, et eleifend eros rhoncus eu. In efficitur arcu eleifend mauris ultrices, mattis laoreet nisi commodo. Suspendisse vitae augue libero. Duis cursus, ante id luctus consectetur, erat odio ullamcorper risus, at placerat diam erat id ipsum. Integer aliquam ornare lectus sed dapibus. Pellentesque viverra tristique ex ac aliquet. Curabitur convallis arcu at rutrum condimentum.

Suspendisse rutrum elit sed turpis tincidunt, sed bibendum lectus faucibus. Pellentesque egestas nisi et consequat bibendum. Sed vestibulum ullamcorper lacus, at aliquet nisi pharetra eu. Proin eu libero vitae tellus interdum bibendum in ac mi. Phasellus tincidunt iaculis odio, non sodales nunc bibendum eu. Donec volutpat orci eget dictum dictum. Vestibulum porttitor, tortor lacinia bibendum sodales, ante orci malesuada nibh, ut fringilla lorem urna id odio. Morbi vehicula tincidunt odio a pharetra.

Donec mollis, neque quis mollis fermentum, orci mauris posuere lectus, quis tincidunt odio augue nec arcu. Donec nibh metus, euismod ac velit et, semper cursus orci. Donec non mi non risus finibus vehicula sit amet in ligula. Etiam sagittis est eu pharetra rhoncus. Fusce tempor non lorem at imperdiet. Vestibulum id dapibus elit. Sed mollis, nulla molestie tristique hendrerit, tortor ante cursus quam, sed sodales mauris ipsum sit amet lectus. In ut sem erat. In maximus lorem in nunc blandit, nec suscipit arcu rhoncus. Nunc hendrerit nisi nec enim blandit, a efficitur lorem auctor. Suspendisse potenti. Vestibulum laoreet orci arcu, et sodales turpis tincidunt eget. Aenean molestie est non mattis aliquam.

Proin ut molestie dolor, at condimentum metus. Vestibulum ornare neque et ligula rhoncus convallis. Cras eget est eget dolor sodales pharetra. Etiam nec magna vel tortor interdum efficitur eget vel lectus. Sed molestie faucibus fermentum. Duis ut lorem placerat, pharetra ex sed, convallis dolor. Fusce sit amet scelerisque ligula. Proin lacus libero, facilisis quis tincidunt facilisis, vulputate et ligula.

Suspendisse interdum eu nunc vitae egestas. Vestibulum commodo metus in congue lobortis. Donec tincidunt, orci id egestas consequat, orci enim semper odio, non imperdiet turpis est id nisi. Proin nulla enim, ultricies ac nunc vitae, interdum tempor metus. Nullam ut convallis metus. Etiam interdum id ipsum sed porttitor. Vivamus vel tortor convallis, auctor arcu id, rhoncus neque. Duis eget mauris nulla. Donec nec leo aliquet, tincidunt est condimentum, dignissim felis. Integer aliquam quam sit amet nibh consequat rhoncus. Cras pellentesque quis sapien ut vestibulum.

Aliquam vel laoreet eros, at luctus ante. In sit amet aliquam nibh. Nullam libero elit, congue at tincidunt id, fringilla eget nulla. Suspendisse tempus odio massa, et viverra justo finibus et. Fusce quis tellus nec mi cursus rutrum eget in nulla. In lectus nibh, ultricies sed malesuada euismod, pulvinar id elit. Vivamus aliquet nunc eu auctor elementum. In hac habitasse platea dictumst. Pellentesque pretium urna vel dui accumsan sollicitudin ornare et leo. Nam vestibulum mattis placerat.

Vestibulum at dignissim ex. Curabitur tempor egestas molestie. Suspendisse potenti. Suspendisse convallis dolor ligula, sed commodo nibh suscipit vel. Suspendisse facilisis consectetur pellentesque. Mauris varius suscipit pulvinar. Ut fermentum, elit sit amet lobortis aliquam, mauris dolor semper risus, quis scelerisque risus lorem vitae felis. Phasellus eget augue sagittis lorem posuere rutrum.

Donec luctus sem at justo mollis congue. Ut eget vestibulum orci. Nullam molestie, risus a mollis suscipit, mauris erat dignissim tellus, in posuere urna velit eget nulla. Suspendisse aliquam, sem sed fermentum fermentum, tortor arcu consectetur justo, eget consequat lorem nibh eget massa. Nunc vitae ligula ultrices, cursus sapien vulputate, posuere dolor. Nam venenatis ipsum erat, id vulputate sapien viverra non. Etiam ut imperdiet mauris. Quisque quis ante auctor, imperdiet odio sit amet, vulputate nulla. Duis volutpat massa justo, sit amet dictum ante ornare quis. Vivamus viverra in mauris at tristique. Morbi ultrices, nunc vitae euismod rhoncus, mauris tortor euismod nunc, ac vestibulum dolor magna non justo. Ut eget lectus ornare, volutpat leo ut, tempus nisi. Vivamus dolor neque, tincidunt sit amet suscipit vel, viverra ut urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla tempus purus at velit imperdiet vehicula. Praesent ac quam sit amet nisl elementum venenatis nec sit amet lacus.

Sed consequat arcu ut fermentum dapibus. Integer sed egestas diam, eget lacinia nulla. Nam a libero in diam maximus rutrum vel quis elit. Nulla facilisi. Integer eu venenatis eros, et tincidunt arcu. In quam leo, tempus sed nibh nec, pellentesque sollicitudin urna. Aliquam id sapien sit amet nibh gravida blandit. Sed bibendum, sem id volutpat lacinia, nibh orci dapibus nibh, vel auctor lectus neque consectetur arcu. Morbi tincidunt quam erat, vitae vestibulum erat semper quis. Aliquam venenatis sollicitudin nunc, elementum dictum lorem dignissim vitae. Aenean tincidunt mauris a erat aliquet, id hendrerit odio tincidunt.

Vivamus vel tortor ipsum. In fringilla volutpat lectus, id cursus ex posuere at. Aliquam enim metus, condimentum quis nisl in, consectetur cursus turpis. Fusce sapien turpis, lacinia at magna ac, fermentum ultricies ex. Sed sem ex, dictum nec nisi eget, facilisis maximus erat. Etiam ipsum metus, maximus at quam a, molestie dictum turpis. Proin purus risus, faucibus in hendrerit bibendum, vulputate nec dolor. Sed in vehicula arcu. Donec molestie urna est. Curabitur consequat orci eu lorem rutrum lacinia. Suspendisse ut dictum eros, eget feugiat tortor."

time ./client $1 "testando unicode symbols: 😻😘♥☕✅"